services:
  site:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: facilito-site
    restart: unless-stopped
    networks:
      - edge
    volumes:
      - ./dist:/usr/share/nginx/html:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.facilito-site.rule=Host(`facilito.ar`) || Host(`www.facilito.ar`)
      - traefik.http.routers.facilito-site.entrypoints=websecure
      - traefik.http.routers.facilito-site.tls=true
      - traefik.http.services.facilito-site.loadbalancer.server.port=80
      - traefik.docker.network=edge

networks:
  edge:
    external: true
